# Generated by Django 4.2 on 2023-04-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status_id',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='askme.status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='answer_id',
            field=models.ManyToManyField(null=True, to='askme.answer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status_id',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='askme.status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags_id',
            field=models.ManyToManyField(null=True, to='askme.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
