# Generated by Django 4.2 on 2023-04-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_answer_correct_alter_answer_status_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer_id',
            field=models.ManyToManyField(blank=True, to='askme.answer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
